### ISSUE TITLE
Can't Import Image Asset

### ISSUE THREAD

**Issue by danielbarrosamorim** [mfractor/mfractor-feedback#144]
When I click  Choose Image from Import Image Asset nothing happens. So I can't set the image.

##Installation Information

```
--Platform Information--
Operating System: Mac
OS: Unix
OS Service Pack: 
OS Version: Unix 19.0.0.0
--MFractor Information--
Product Name: MFractor
Product Version: 3.8.23
Product Variant: Visual Studio Mac
Product Variant Version: 8.4.0.1936
Product SKU: MFRACTOR-VS-MAC
Commit SHA: c435e4f6cbb99f4728226cd0209851b54001a935
Revision: 3813
Branch: master
Date: 17/10/2019 4:47:27 AM (UTC)
Agent: Local
Installed extensions:
	
```

**Comment by danielbarrosamorim** [comment]
![Import_Image_Asset](https://user-images.githubusercontent.com/7776295/67812962-20d2fe80-fa7f-11e9-9861-149478943fd1.png)

**Comment by ravero** [comment]
Hi Daniel,
Thanks for your feedback. We've already identified this issue and its going to be addressed in a future update. We'll keep you posted as soon as we release it.

**Comment by matthewrdev** [comment]
@danielbarrosamorim Could you please upgrade to v3.8.24 and retest this? This release should fix this issue however I'd like to double check with you.

**Comment by danielbarrosamorim** [comment]
@matthewrdev Sure, but how can I get this new version? It is not available on VS updates.

**Comment by matthewrdev** [comment]
@danielbarrosamorim Please update Visual Studio Mac to 8.3.7, you should receive an update notification for MFractor then.

Alternatively, you can use the following link: http://addins.monodevelop.com/Stable/Mac/8.3.7/MFractor.VS.Mac.MFractor-3.8.24.mpack

Please note that this release targets Visual Studio Mac 8.3.7 and may not work on previous releases.

**Comment by danielbarrosamorim** [comment]
@matthewrdev I dit it, but the issue remains the same. If you need more info or even want to access my mac remotely please let me know.

Here is my About info: 
=== Visual Studio Community 2019 for Mac ===

Version 8.3.7 (build 1)
Installation UUID: d1f217ac-e229-4870-8d95-2d0b764769eb
	GTK+ 2.24.23 (Raleigh theme)
	Xamarin.Mac 5.16.1.24 (d16-3 / 08809f5b)

	Package version: 604000208

=== Mono Framework MDK ===

Runtime:
	Mono 6.4.0.208 (2019-06/07c23f2ca43) (64-bit)
	Package version: 604000208

=== NuGet ===

Version: 5.3.0.6192

=== .NET Core SDK ===

SDK: /usr/local/share/dotnet/sdk/3.1.100-preview2-014569/Sdks
SDK Versions:
	3.1.100-preview2-014569
	3.0.100
	3.0.100-preview8-013656
	2.2.101
	2.1.701
	2.1.700
	2.1.505
MSBuild SDKs: /Library/Frameworks/Mono.framework/Versions/6.4.0/lib/mono/msbuild/Current/bin/Sdks

=== .NET Core Runtime ===

Runtime: /usr/local/share/dotnet/dotnet
Runtime Versions:
	3.1.0-preview2.19525.6
	3.0.0
	3.0.0-preview8-28405-07
	2.2.7
	2.2.0
	2.1.13
	2.1.12
	2.1.11
	2.1.9

=== Xamarin.Profiler ===

Version: 1.6.12.26
Location: /Applications/Xamarin Profiler.app/Contents/MacOS/Xamarin Profiler

=== Updater ===

Version: 11

=== Xamarin.Android ===

Version: 10.0.6.2 (Visual Studio Community)
Commit: xamarin-android/d16-3/c407838
Android SDK: /Users/danielamorim/Library/Developer/Xamarin/android-sdk-macosx
	Supported Android versions:
		8.1 (API level 27)

SDK Tools Version: 26.1.1
SDK Platform Tools Version: 29.0.5
SDK Build Tools Version: 29.0.2

Build Information: 
Mono: mono/mono/2019-06@476d72b9e32
Java.Interop: xamarin/java.interop/d16-3@5836f58
LibZipSharp: grendello/LibZipSharp/d16-3@71f4a94
LibZip: nih-at/libzip/rel-1-5-1@b95cf3fd
ProGuard: xamarin/proguard/master@905836d
SQLite: xamarin/sqlite/3.27.1@8212a2d
Xamarin.Android Tools: xamarin/xamarin-android-tools/d16-3@cb41333

=== Microsoft Mobile OpenJDK ===

Java SDK: /Users/danielamorim/Library/Developer/Xamarin/jdk/microsoft_dist_openjdk_1.8.0.25
1.8.0-25
Android Designer EPL code available here:
https://github.com/xamarin/AndroidDesigner.EPL

=== Android SDK Manager ===

Version: 1.4.0.65
Hash: c33b107
Branch: remotes/origin/d16-3
Build date: 2019-10-10 12:15:44 UTC

=== Android Device Manager ===

Version: 1.2.0.116
Hash: d2b2af0
Branch: remotes/origin/d16-3
Build date: 2019-10-10 12:16:06 UTC

=== Apple Developer Tools ===

Xcode 11.2 (15526)
Build 11B52

=== Xamarin.Mac ===

Version: 6.6.0.12 (Visual Studio Community)
Hash: e3c2b406d
Branch: xcode11.2
Build date: 2019-11-01 00:12:07-0400

=== Xamarin.iOS ===

Version: 13.6.0.12 (Visual Studio Community)
Hash: e3c2b406d
Branch: xcode11.2
Build date: 2019-11-01 00:12:08-0400

=== Xamarin Designer ===

Version: 16.3.0.256
Hash: 8a223bfd7
Branch: remotes/origin/d16-3
Build date: 2019-11-01 21:02:02 UTC

=== Xamarin Inspector ===

Version: 1.4.3
Hash: db27525
Branch: 1.4-release
Build date: Mon, 09 Jul 2018 21:20:18 GMT
Client compatibility: 1

=== Build Information ===

Release ID: 803070001
Git revision: 9245c93bbca71766f0150b84e30dd42c394bd259
Build date: 2019-11-04 21:08:08+00
Build branch: release-8.3
Xamarin extensions: ea50d7eae9677fbbd7ff7578a7d1429b9946a728

=== Operating System ===

Mac OS X 10.15.1
Darwin 19.0.0 Darwin Kernel Version 19.0.0
    Thu Oct 17 16:17:15 PDT 2019
    root:xnu-6153.41.3~29/RELEASE_X86_64 x86_64

=== Enabled user installed extensions ===

LiveXAML 1.3.51
Xamarin Extensions - Syncfusion 17.3.0.9
MFractor 3.8.24

**Comment by matthewrdev** [comment]
@danielbarrosamorim Let's arrange a call for the next few days. Please email me (matthew@mfractor.com) and we'll get it solved.

**Comment by matthewrdev** [comment]
@danielbarrosamorim This appears to be caused by a Xamarin.Mac + Catalina issue specifically related to the open file dialog. Based on the commit history of MonoDevelop, this looks like it will be addressed in the coming Visual Studio Mac 8.4 release.

Please see the following links:
https://github.com/xamarin/xamarin-macios/issues/6474
https://github.com/mono/monodevelop/commit/1d53dedc00145e4c2c526d672e589ee49fb7c4f8

I'll continue investigating and see if we can fix the issue in the interim.

**Comment by matthewrdev** [comment]
@danielbarrosamorim Can I please confirm that this is still an issue for you?

Using MFractor 3.9 and VS Mac 8.3.10 on Catalina I was not able to reproduce this issue.

**Comment by matthewrdev** [comment]
@danielbarrosamorim As I haven't heard back that this is still an issue or not, and I have confirmed it working with other customers who are using Catalina, I am closing this ticket.

If this issue still persists, please reopen this ticket.
