### ISSUE TITLE
Go To Code Behind, Go To XAML View, Go To VM missing on MFractor windows

### ISSUE THREAD

**Issue by lachlanwgordon** [mfractor/mfractor-feedback#282]
On VS Mac you can use Alt+Shift+1/2/3 to navigate between CodeBehind, XAML/Razor and ViewModel. You can also access these from right click menu.

I think when they used to be here they used a different hotkey to Mac, maybe Alt+1/2/3? My preference would be for the same hotkeys on both platforms, but VS Win and VS Mac have such different hotkeys that might to be reasonable.

I can't find these anywhere in VS Windows although I think I remember seeing this in an earlier build.

Using MFractor 4.2.11 and VS 16.6.4

**Comment by ravero** [comment]
Hi @lachlanwgordon,
Unfortunately we couldn't keep the same keys because it was clashing to existing ones on VS for Windows. On the final release of MFractor we have mapped it to ALT+1/2/3. Take a look at this:

![mvvm-navigation](https://user-images.githubusercontent.com/1834963/88243761-dc6c3c00-cc67-11ea-9dca-7a4cdbbef61c.png)

**Comment by lachlanwgordon** [comment]
I thought that clash might be the case. When you say Final do you mean next version, or should I have this now?

Alt+1/2/3 aren't working for me and I can't see them in my right click menu either.

<img width="520" alt="Screen Shot 2020-07-23 at 11 13 41 am" src="https://user-images.githubusercontent.com/29908924/88244025-b4b3bd00-ccd5-11ea-80db-56bcd4ccda97.png">

**Comment by ravero** [comment]
By final I mean the post-beta version of the Windows extension. It's implemented on the current stable release.
This sample picture you've taken by right-clicking on what file? I'll need to investigate, sometimes the menu items doesn't appear if MFractor is still loading in background just after you load the project.

**Comment by lachlanwgordon** [comment]
Hmm, I've just opened a different solution and it works fine there, but doesn't work in the solution I'm working on. To be fair, it is a pretty chunky solution with 37 projects.

Whoops, not much context in that screen shot, here's on in a xaml and one in a xaml.cs.

<img width="939" alt="Screen Shot 2020-07-23 at 11 24 37 am" src="https://user-images.githubusercontent.com/29908924/88244418-29d3c200-ccd7-11ea-8298-d42ca679503c.png">

<img width="1040" alt="Screen Shot 2020-07-23 at 11 23 32 am" src="https://user-images.githubusercontent.com/29908924/88244377-027cf500-ccd7-11ea-940a-a7da9e44bb90.png">

**Comment by ravero** [comment]
If you use the keyboard shortcuts directly, does it works?
Maybe the size of the solution could be causing the issue. Visual Studio queries the extension every-time its about to show the right-click menu. It could be timing out our check because we need to resolve the related objects and maybe its getting too long on this big solution.

I'll investigate this.

**Comment by lachlanwgordon** [comment]
Nope, keyboard shortcuts do nothing.

I actually want to use this with .razor/.razor.cs, but tested with XAML too. Both are behaving the same.

Could you speed thing up by only querying within the active project rather than the whole solution?

Also feel free to put this aside for now if you've got more important things going on, I don't think this affects many users.

**Comment by matthewrdev** [comment]
@lachlanwgordon Yes, we can speed this up by only querying the current project. Cross-project resolution/solution scanning is a new addition (see https://github.com/mfractor/mfractor-feedback/issues/254) which came with a potential performance hit.

Maybe a solution for this is for a feature flag to disable solution scanning?

**Comment by lachlanwgordon** [comment]
Ah, and a new addition that came from me requesting it.

Yeah, if there was a per solution option to turn it on or off that would be cool, and would fix all the use cases I've seen so far.

Maybe it could be even more powerful to configure which assemblies should be scanned. E.g. When I'm working in a certain project `MyApp.Forms` i want to me able to also scan `MyApp.Core` but ignore all the others. This may be a lot of work, only to  make a confusing feature that wouldn't be used much.

**Comment by matthewrdev** [comment]
@lachlanwgordon Given our discussions in Thursday's support call, and that this is surfacing in the mobile blazor bindings project, I think that the in-memory workspace/solution/project copy is not generated successfully.

Other customer issues (#291, #271 ) has the same symptoms as this: features dependant on projects/project files are not populating. All of these issues seem related and are explainable if the shadow-model generation fails.

**Comment by matthewrdev** [comment]
@lachlanwgordon I've located the cause of this issue, the workspace model is failing to get the GUID for the project when it opens, causing everything to unravel and for the workspace to not replicate correctly.

Fixing this issue will resolve many other issues customers are reporting.

**Comment by lachlanwgordon** [comment]
Excellent, glad this led somewhere useful instead of just an edge case in my weird project.

**Comment by matthewrdev** [comment]
@lachlanwgordon Think I've nailed it.

This was a combination of several factors:

 * Our workspaces events were registered twice.
 * We were failing to retrieve the project GUID.
 * There were some bugs in traversing solution folders to discover inner projects.

Looking like this is fixed. Will continue testing and confirm.

**Comment by matthewrdev** [comment]
@lachlanwgordon Can I get you to retest this on the latest Windows release? v4.2.12

**Comment by lachlanwgordon** [comment]
It still doesn't work in the Mobile Blazor Bindings Solution but does work in other apps.

**Comment by matthewrdev** [comment]
@lachlanwgordon Which files and projects does the MVVM navigation shortcuts *not* appear/work in? I'll dive in and investigate each one specifically.

**Comment by lachlanwgordon** [comment]
Take a look at this branch https://github.com/lachlanwgordon/MobileBlazorBindings/tree/mfractorCodeNavigationRepro

In the MobileBlazorBindingsHelloWorld project I've added a SampleXamlPage/SampleXamlPageViewModel and a SampleRazorPage/SampleRazorPageViewModel. Alt+1/2/3 and right click navigation doesn't work in any of these files.
